server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://172.17.196.112:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 172.17.196.112
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    user-service: /user/**
ribbon:
  ConnectTimeout: 3000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
# 开启和暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


