
server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    user-service: /user/**
ribbon:
  ConnectTimeout: 3000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
# 开启和暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# JWT
jwt:
  header: Authorization
  secret: luck
  #token有效期一天
  expiration: 86400
  pubKeyPath: "../logistics/mf-gateway/src/main/resources/pub.key"
  cookieName: "lucky"
filter:
  allowPaths:
    - /api/item/user/
    - /api/item/accredit
