server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.94.95.93:3306/logistics?allowMulitQueries=true&useUnicode=true&characterEncoding=utf8
    username: jinzhou
    password: Tonsan123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
logging:
  config: classpath:logback-spring.xml
eureka:
  client:
    service-url:
      defaultZone: http://172.17.196.112:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 172.17.196.112
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mybatis/*.xml
# 开启和暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
jwt:
  secret: luck # 登录校验的密钥
  pubKeyPath: "../logistics/mf-gateway/src/main/resources/pub.key"
  priKeyPath: "../logistics/mf-gateway/src/main/resources/pri.key"
  expire: 30 # 过期时间,单位分钟
  cookieMaxAge: 1800
  cookieName: lucky
