spring:
  application:
    name: item-service
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 47.94.95.93:22122
