spring:
  datasource:
    url: jdbc:mysql://rm-m5es50j9lfj56x323jo.mysql.rds.aliyuncs.com:3306/logistics?allowMulitQueries=true&useUnicode=true&characterEncoding=utf8
    username: logiuser
    password: Tonsan123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mybatis/*.xml
logging:
  config: classpath:logback-spring.xml
# 开启和暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

jwt:
    secret: luck # 登录校验的密钥
    pubKeyPath: "../logistics/mf-gateway/src/main/resources/pub.key"
    priKeyPath: "../logistics/mf-gateway/src/main/resources/pri.key"
    expire: 30 # 过期时间,单位分钟
    cookieMaxAge: 1800
    cookieName: lucky

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 47.94.95.93:22122
