server:
  port: 10086
eureka:
  datacenter: prod
  environment: prod
  client:
    #关闭eureka自我注册
    #fetch-registry: false
    #register-with-eureka: false
    service-url:
      defaultZone: http://172.17.196.112:10086/eureka
  instance:
    ip-address: 172.17.196.112
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoint:
    shutdown:
      enabled: true
